### ISSUE TITLE
Request for updated tools: Metal 3.0 beta compilers,glslang, spirv-cross and Slang..

### ISSUE THREAD

**Issue by oscarbg** [tgjones/shader-playground#111]
Hi,

main motivation is Metal 3.0 shader tools for Windows (I have 3.0b4 locally )for testing Metal 3.0 mesh shaders and atomic floats support..
also not really urgent but seeing glslang is >1.5 years old and spirv-cross and slang are both >1 year old, sure many fixes and support for new VK exts have gone on to it..
suggestion only but maybe update to:
*https://github.com/KhronosGroup/glslang/releases/tag/11.11.0
*https://github.com/shader-slang/slang/releases/tag/v0.24.14
*spirv-cross trunk or in sync with latest Vulkan SDK 1.3.224 which is:
spirv-cross --revision
Git commit: 61c603f3 Timestamp: 2022-08-22T10:02:05

thanks..

**Comment by tgjones** [comment]
Thanks @oscarbg - I've

* added Metal 3.0 beta 4
* updated glslang
* added Slang v0.24.20

I'm will push these changes to the production server shortly.

**Comment by oscarbg** [comment]
thanks!
