### ISSUE TITLE
Support multiple versions of each compiler

### ISSUE THREAD

**Issue by tgjones** [tgjones/shader-playground#14]

**Comment by tfoleyNV** [comment]
I would appreciate having version information for each compiler be visible in the HTML UI, even if the option to switch between versions isn't available right away. Slang is still in a pre-1.0 state and we release versions quite often, so if people submit bug reports based on behavior they see in the shader playground, I'd like to know what compiler version that was to speed up my work in reproducing the issue.

Also: thanks for setting up such an awesome tool! Please let me know if there is anything the Slang project can do to make integration better/easier.

**Comment by tgjones** [comment]
This is definitely something I wanted to do, in advance of actually supporting multiple versions - I’ll look at doing it in the next few days.

And thanks! If I hit any obstacles I’ll let you know. Slang has great docs, especially compared to most of the other compilers I’ve integrated, so the initial integration was straightforward.

Likewise if you have any other suggestions for improving Shader Playground or Slang integration specifically, please let me know.

(I’ve followed your shading language work since Spark. It’s exciting to see Slang taking shape.)

**Comment by tgjones** [comment]
@tfoleyNV Done. I went ahead and just did this whole multiple-version feature, and then took the opportunity to add the two new versions of Slang that you've released in the last few days.

(It would be really cool to see people using Shader Playground permalinks when reporting bugs to projects like yours. Hopefully that will also speed up the repro process.)
