### ISSUE TITLE
Output spirv as C array

### ISSUE THREAD

**Issue by jesta88** [tgjones/shader-playground#21]
This output would be very useful for small in-engine shaders that you just want embedded in the code.

Example: https://github.com/bkaradzic/bgfx/blob/master/src/vs_clear.bin.h

And here's one way to convert to array: https://github.com/Novum/vkQuake/blob/master/Shaders/bintoc.c

**Comment by tgjones** [comment]
Done! I've implemented it for all output binaries, not just SPIR-V.

<img width="151" alt="download-button" src="https://user-images.githubusercontent.com/102049/42045870-30da75fe-7b2f-11e8-880a-929e63d12f27.PNG">

<img width="675" alt="c-header" src="https://user-images.githubusercontent.com/102049/42045879-34171f38-7b2f-11e8-9d72-5ce3f69d9395.PNG">
