### ISSUE TITLE
MSL (Metal) Support would be interesting to add

### ISSUE THREAD

**Issue by natbro** [tgjones/shader-playground#35]
... at least as a target.

**Comment by tgjones** [comment]
MSLis already there as a target for several of the compilers - HLSLcc, GLSL optimizer, SPIRV-Cross, HLSLParser.

I am very interested in supporting MSL as an input language. As far as I can tell the output of Apple’s compiler is something very close to LLVM IR. But it will require a macOS VM hosted somewhere, and they’re not cheap - I’m waiting to see how my Patreon goes before committing to that.

**Comment by natbro** [comment]
nice - i didn't see it as a target, sorry for missing that!

drop me a line natb@valvesoftware.com, would be interested to chat about macOS VM hosting.

**Comment by tgjones** [comment]
Closing in favour of #99.
