### ISSUE TITLE
SPIRV-Cross to ISPC - add better naming to ISPC output

### ISSUE THREAD

**Issue by jonckennedy** [tgjones/shader-playground#36]
Looking at http://shader-playground.timjones.io/7b188536275bddba2caad31d92a6691a

The SPIRV files obviously have some random temp names and this is appearing in the ISPC file as an entry point name. Using the '--ispc-interface-name <name>' option will override this and should allow you to add a more sensible names for better clarity.

**Comment by tgjones** [comment]
Thanks! I'm also pretty sure those GUIDs with hyphens aren't valid identifiers...

I've fixed it now, with a configurable ISPC interface name that defaults to "Shader", so existing examples like your link above will now produce valid code.
