### ISSUE TITLE
New compiler - Rust GPU

### ISSUE THREAD

**Issue by tgjones** [tgjones/shader-playground#38]
https://github.com/MaikKlein/rlsl

**Comment by didito** [comment]
This should probably change to rust-gpu

https://maikklein.github.io/rlsl-update3/
https://github.com/EmbarkStudios/rust-gpu

**Comment by tgjones** [comment]
Some helpful guidance here: https://twitter.com/_tim_jones_/status/1319333991829393411

And v0.2 has been released: https://github.com/EmbarkStudios/rust-gpu/releases
