### ISSUE TITLE
Slow down the compile as you type delay, to reduce server load and increase percieved responsiveness

### ISSUE THREAD

**Issue by rys** [tgjones/shader-playground#44]
Currently the canonical playground runs compile-as-you-type (`compileCodeTimeout`, [link](https://github.com/tgjones/shader-playground/blob/958865e3d18beef5fb4dd534dd538262263ef3ce/src/ShaderPlayground.Web/wwwroot/js/site.js#L463)) 500ms after you stop typing, which is quite aggressive and easy to hit as you continue to make changes.

Increasing it would reduce the load on the server, and perceptual responsiveness would therefore increase when lots of people are using the playground at the same time, even though it takes longer to kick off an as-you-type compile when you stop smashing the keys.

**Comment by tgjones** [comment]
That's a good idea. I should probably record more stats on usage so I know how heavily the server is being hit at peak times. But I guess I could increase it to 2s without people noticing too much?

**Comment by rys** [comment]
No real harm in trying 2s I think!

**Comment by tgjones** [comment]
Sorry for the delay, I've just fixed this. Going to deploy a new version now (the other change being that for compilers with only a "trunk" version, it now shows you when I last updated it from trunk).
