### ISSUE TITLE
Hangs and unspecified errors

### ISSUE THREAD

**Issue by giordi91** [tgjones/shader-playground#45]
I have been trying to use the playground but I only managed to get something (super slowly ) out of DXC, everything else hangs and a pop up show up saying unspecified error.

I tried on chrome, firefox and edge same issues. They should be all up to date. Any thoughts on the matter?

```

﻿
www.googletagmanager…?id=UA-5166698-11:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
az416426.vo.msecnd.n…scripts/a/ai.0.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/Api/Compile:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)

```

Those are the errors I managed to get from the console from chrome. Only the last one might be related. 

I have been using the website before with great success, not sure what happened. 

Cheers

**Comment by tgjones** [comment]
Hi, I'm sorry for the delay in replying. Are you still getting the same errors?

**Comment by giordi91** [comment]
No worries, I tried the other day and seems to be working :) I will let you know if I see it again.

Cheers
