### ISSUE TITLE
Make caret configurable

### ISSUE THREAD

**Issue by MattSutherlin** [tgjones/shader-playground#46]
I love shader-playground but it's always jarring to use it since I don't otherwise text edit with a block caret.  My personal preference would be to just make it a "standard" line caret, but in the interest of making everyone happy it'd be great if there was a setting for this.

**Comment by tgjones** [comment]
That's always annoyed me too! But I never remembered to fix it. Thanks for the reminder :)

**Comment by MattSutherlin** [comment]
Sooooooooo much better.  Thank you!
