### ISSUE TITLE
missing tools

### ISSUE THREAD

**Issue by Trass3r** [tgjones/shader-playground#47]
Many tools are listed in the readme but I can't find some of them like SMOL-V and spirv-cross on your site http://shader-playground.timjones.io/
Especially interested in spirv-cross. It should be possible to compile a shader to spirv and back, to see what optimizations have been done.

**Comment by tgjones** [comment]
The list of compilers in the dropdown depends on what the input is. For example, if you "chain" a compiler to SPIR-V output, then you'll see both SPIRV-Cross and SMOL-V as available compiler options:

<img width="1639" alt="Screenshot 2019-06-02 at 12 23 09" src="https://user-images.githubusercontent.com/102049/58760555-51932400-8531-11e9-97b2-74075be8d9a5.png">

Here's an example of compiling from GLSL to SPIR-V using glslang, and then from SPIR-V back to GLSL using SPIRV-Cross:

http://shader-playground.timjones.io/1172d554d38ed3f67734951a699bf320

**Comment by Trass3r** [comment]
Ah thanks, exactly what I was looking for.
I see it's even shown in the readme screenshot, but esp. on a mobile you won't notice those details.
Maybe the list of supported tools could be better structured by input, stage, etc.

Some quick feedback from testing GLSL -> spirv-opt -> spirv-cross:
* spirv-cross always has PSMain as the default entrypoint. Is that option even needed? SPIR-V does contain `OpEntryPoint`, at least when compiled from GLSL.
* Do you explicitly pass --strip-debug to spirv-opt? All the variable names are lost. Doesn't seem to be [included ](https://github.com/KhronosGroup/SPIRV-Tools/blob/0125b28ed4214d1860696f22d230dbfc965c6c2c/source/opt/optimizer.cpp#L155) in `-O`.
* Related: would be good to see the tool commandline somewhere (like godbolt when hovering over the icon next to the toolname).
* Commandline modification like in godbolt would be nice.
* Merge errors into the default output pane (in red). Currently you only get a blank pane (see item 1) and wonder what's going on and have to switch.
* Show errors inline like compiler-explorer.
* When removing the compiler in the middle of the chain, everything after it gets removed too. Maybe it could be smarter about this and reattach spirv-cross to the GLSL compiler in this case.

**Comment by tgjones** [comment]
@Trass3r great feedback - would you mind logging these as separate issues, so I can keep track of them better?
