### ISSUE TITLE
support custom commandline options

### ISSUE THREAD

**Issue by Trass3r** [tgjones/shader-playground#49]
Complementary to #28.
Just like compiler explorer.

**Comment by tgjones** [comment]
The reason I haven't done this yet is that I don't know how to parse arbitrary options in a "safe" way, that doesn't allow a potential attacker to modify / destroy the VM that Shader Playground runs on. I guess I need to spend some time researching it.

**Comment by tgjones** [comment]
I've started doing this for individual compilers, when I think it's "safe enough" to do, which I think is how I need to proceed for the moment... at least until I can have compilers running in a sandbox environment, which I think is how Compiler Explorer does it.
