### ISSUE TITLE
show errors more clearly

### ISSUE THREAD

**Issue by Trass3r** [tgjones/shader-playground#50]
http://shader-playground.timjones.io/051cc4733f7aebdd78cb7b12c48cb835
It shows the reflection tab which is just empty, very puzzling.
The error tab shows that the default (and unnecessary? #47) entrypoint setting is wrong.

Error messages should be merged into the default output (in red).

And/or shown inline like compiler-explorer does (where applicable).

**Comment by tgjones** [comment]
* I've made "Entry point" optional for spirv-cross, because by default it's going to take the value of `OpEntryPoint`).
* I've also fixed the bug that showed the reflection tab, it was supposed to show errors if there were any
