### ISSUE TITLE
Unexpected error while compining HLSL shader with DXC

### ISSUE THREAD

**Issue by sunillnaik** [tgjones/shader-playground#55]
The shader playground is tooo slow and fails to compile with below error.
![unexpected_error](https://user-images.githubusercontent.com/44568355/64151865-3f918c00-ce66-11e9-8a96-26206f062a93.png)

**Comment by tgjones** [comment]
Thanks - I've restarted the web server, should be fixed now.

**Comment by sunillnaik** [comment]
Cool! Thanks
