### ISSUE TITLE
RGA 2.3 and 2.4 support

### ISSUE THREAD

**Issue by silvesthu** [tgjones/shader-playground#67]
Is there any plan to update RGA support to 2.3?
It will be nice to have the DX12 mode.

**Comment by tgjones** [comment]
Also RGA 2.4 has been released.

**Comment by tgjones** [comment]
RGA 2.3 and 2.4 (and 2.4.1) are on Shader Playground already. DX12 mode isn't there yet because of [this](https://github.com/GPUOpen-Tools/radeon_gpu_analyzer/issues/77).
