### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by ben-clayton** [tgjones/shader-playground#73]
Hi @tgjones,

Thank you for building such a useful tool!

I've been investigating the work required to implement #72. From what I've seen, making the code changes would not be particularly hard. However, I'm struggling a bit to get the project building using the `build.ps1` script:

* There's a number of compiler URLs that are now broken. For example, [dxc](https://github.com/tgjones/shader-playground/blob/087baf093f868b2c98a84f729e60a7a23635ddd9/build.cake#L77), and the [radeon driver](https://github.com/tgjones/shader-playground/blob/087baf093f868b2c98a84f729e60a7a23635ddd9/build.cake#L272) no longer fetch (there might be more, these are what I hit so far).
* The project uses `netcoreapp2.2`, [which is now deprecated](https://dotnet.microsoft.com/download/dotnet-core/2.2). While you can go and manually download this, it's a bit of a barrier and would be nice to update to something longer-term supported.
* There's [hardcoded paths to 7-zip](https://github.com/tgjones/shader-playground/blob/087baf093f868b2c98a84f729e60a7a23635ddd9/build.cake#L262), which are undocumented, but are easily solvable.

I've spent a bit of time trying to fix up some of these issues, and I've been playing with a docker file that tries to simplify building the project. However, I've noticed that there has been little activity on the project this year.
Are you continuing to maintain this project and/or accepting pull requests?

Thank you again for such a great tool!

Cheers,
Ben

**Comment by tgjones** [comment]
Hi @ben-clayton - I'm sorry for not replying before! To answer your questions:

* Yes, I am continuing to maintain this project. As you've noticed there are periods when I don't really touch it, but it's definitely not abandoned.
* Yes, I do (gratefully) accept pull requests.

And yes, building the project is hard :( I've only ever built it on my computer, and when I changed computers recently I had to bring across my local build folder otherwise I couldn't get it building either! Not great. Ideally I'd have it buildable on GitHub Actions but it requires so many gigabytes of tools that I don't know if it's viable. A Docker file sounds interesting. But some of the things you mentioned sound like they're just broken - I'll try to take a look in the next few days.

**Comment by ben-clayton** [comment]
Hi @tgjones,

Thanks for getting back to me.

> A Docker file sounds interesting

Having successfully created (mostly) hermetic builds on Linux, I think its a good way to go, but I did struggle with the windowsy-ness of all this. Finding a nice Windows development base docker image was confusing, and then finding the right set of VS Build Tools to install was difficult, and I don't think I found the magic combination before putting the effort on ice. There's an [MSDN document about the process here](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019). The tricky bit for Shader Playground is that you have to install the right .NET packages for the server (including the now deprecated `netcoreapp2.2`), C++ toolchains for the various compilers that are built, plus the CMake and git tools that's expected. I'm sure it's totally doable, just a laborious trial-and-error task.
It would also be great to have those Cake download tasks only perform if the file isn't already downloaded - this would greatly speed up the effort.

> But some of the things you mentioned sound like they're just broken

I managed to find replacement URLs for many of the downloads without too much pain. The one I really struggled with was the radeon driver download. It looks like AMD are now doing some clever tricks to prevent you from simply `curl`-ing their downloads. It might be worth reaching out to them to see if they can provide the dlls in a way that doesn't involve downloading and pulling apart their driver.

> I'll try to take a look in the next few days.

Thanks. I'm happy to try and collaborate on this, especially if there are bits I've already done. I'll try to resurrect my efforts, and maybe throw some PRs your way in the next few days. Please don't feel obliged to accept them - they're there if they help you get things up and building again.

All the best,
Ben

**Comment by tgjones** [comment]
> It would also be great to have those Cake download tasks only perform if the file isn't already downloaded

In theory this happens already (unless there's a bug), but only for compiler releases with version numbers in the URL. All the "trunk" downloads happen every time.

> It might be worth reaching out to them to see if they can provide the dlls in a way that doesn't involve downloading and pulling apart their driver.

Funnily enough I did reach out to them, which is how I found I could grab those particular files from inside their driver package in the first place. But I'll try reaching out again to see if we can find a workaround for the workaround 😄 

> I'm happy to try and collaborate on this

Thank you, it's much appreciated! I'll dig back into it too and hopefully between us we can make some progress. It would be good for the project in general, if it's possible for people other than me to contribute!

**Comment by ben-clayton** [comment]
Just to let you know I'm still working on this (it's been tougher than I was expecting!)

I'm almost there with a hermetic build. If you're still happy with fixes, I'll start posting PRs shortly.

**Comment by tgjones** [comment]
That sounds great! Did you see that I pushed a few fixes for some of the things you mentioned?

**Comment by ben-clayton** [comment]
I did, thank you.

We still have to figure out how to [download the adrenalin driver](https://github.com/tgjones/shader-playground/blob/master/build.cake#L275) in order to extract out `atidxx64.dll` and `amdvlk64.dll`.

I don't have a solution to this, yet.

**Comment by ben-clayton** [comment]
Okay, I now have an (imperfect) docker based, hermetic build solution that allows me to build everything (with exception to obtaining the dlls found in [the adrenalin driver](https://github.com/tgjones/shader-playground/blob/master/build.cake#L275).

I've found a few other issues along the way that I've fixed.

I've started to spam you with PRs. I have more to come, but want to get the base changes in first.
Please feel free to reject changes if you're not happy with them!

Cheers,
Ben

**Comment by ben-clayton** [comment]
The only remaining build issue that I'm aware of is the adrenalin driver download.
I've creaated https://github.com/tgjones/shader-playground/issues/84 to track this.
