### ISSUE TITLE
Ability to select MSL Version in Spirv-Cross

### ISSUE THREAD

**Issue by cwfitzgerald** [tgjones/shader-playground#97]
Some features require newer versions of MSL, and it would be nice to expose the `--msl-version` flag of spirv-cross so it is willing to generate newer versions.

Valid values appear to be (based on https://developer.apple.com/documentation/metal/mtllanguageversion):
`10000`
`10100`
`10200`
`20000`
`20100`
`20200`
`20300`

**Comment by tgjones** [comment]
I've gone one better - there's now a textbox to enter arbitrary CLI options for SPIRV-Cross. Here's an example of setting `--msl-version 20100 --msl-argument-buffers`:

http://shader-playground.timjones.io/b8cf14e2bc30265ce60b1d095f5c6a3e

**Comment by cwfitzgerald** [comment]
That's super useful! Thanks!
